-- 카테고리 관리자 권한 신청 기능
-- 공용 Oracle DB에서 1회 실행하세요.

CREATE TABLE CATEGORY_MANAGER_REQUEST (
    REQUEST_ID NUMBER PRIMARY KEY,
    MEMBER_NO NUMBER NOT NULL,
    REQUEST_STATUS VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
    REQUESTED_AT DATE DEFAULT SYSDATE NOT NULL,
    PROCESSED_AT DATE
);

CREATE SEQUENCE CATEGORY_MANAGER_REQUEST_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE;

COMMENT ON TABLE CATEGORY_MANAGER_REQUEST IS '카테고리 관리자 권한 신청';
COMMENT ON COLUMN CATEGORY_MANAGER_REQUEST.REQUEST_STATUS IS 'PENDING / APPROVED / REJECTED';
